---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: test-probe
spec:
  encryptedData:
    .dockerconfigjson: AgCzCelXR60w+MDZcdh2W2RhuLwRVkiJe7EbkPh59ZtjVe2Jg0DlAZDMInFOkAT7AFP/4TD97DjzYVJlmubJO49LCW/I38szYBDgw9f3SKxcnQddK4rRxObC9/nd128JiLRYnE0FmJckSObRCclwca5sd4VbWOtAVQuBEyAuFHLtkZineEmUVBLLeYDKAeUD0c6me+oShfF8RVDv+z3qKxu8cCLKiEKyv494JMDOqgg0OHNg8fiQ24dtOGm5L+vp+AnaxlvivnMPsmMl7baP7XFFAKeIpT/eyq2ELxH1jwsS2Rkc32XVWmpjN1bMrEOI9WF5K4FNMzeJHnI+sp7O5FnCg/Xf5tSe8f3Tl8BBrGqlTRsnPK22w6rR2Zeb8gcdvES297AYt85/zvNlxbadPhNymteifCp8iGqen7inWTyDQL5slwkNdhAgILT62dOKzcxoppLk0FRj6udlgAZNjgHWjQa3d5CpzMnNWyL3lKeGggqGtxTM+06zXu/F1FCM7xbQkMCxKS9hsbZhSQNXKuHgB8wXgqzGm7XxtVu6mKOW3wV4pVdkQBCR5YWnrkh1mphQO/FC1leIsxnCeR+RM/vuy7dV83pHjWhm8l+Y3x3+98z8eEJllOETayEZlRwYg7NFdDgJje+g1MvQRAGFBQWZSAgHNCflhWKNj9juUwcermlQrxMieH+UBOqjEidxTHQjZG//lIkaAxhs6MKO3RMOXJVjlDtfv8+IizqMX6HUR7FaCKiSQ/m50+d3emWB6wayNujqWYWtu8zjd9F5hqBXvswY+xyP0uMTbdh6zGLfB3tTBHJ61WjPipCXBfD1PZobS8UpOqdyywBnPO7AJELuTlcdA7hBTmfXvQSK30J+0cFABbvVeBUAIH+XOgM8lY9s+8uAkh5DvRA876Z0qcxSVnI3Tk9GokabCVC+6ih5rVuj/XU2C+z8OXi6Z6YIwgmV
  template:
    metadata:
      name: ghcr-pull
      namespace: test-probe
    type: kubernetes.io/dockerconfigjson
